"""calendar overrides and mt watch

Revision ID: 079c3bb11f74
Revises: bc2c06015352
Create Date: 2026-08-23 21:32:39.816593

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '079c3bb11f74'
down_revision = 'bc2c06015352'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rest_days', sa.JSON(), nullable=False),
    sa.Column('worked_saturdays', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', name='uq_calendar_overrides_year')
    )
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cal_last_check', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('mt_last_check', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('mt_last_result', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_column('mt_last_result')
        batch_op.drop_column('mt_last_check')
        batch_op.drop_column('cal_last_check')

    op.drop_table('calendar_overrides')
    # ### end Alembic commands ###
