"""employee contractor flag

Revision ID: 094514885c4c
Revises: 1a6936ce2cb4
Create Date: 2026-08-22 23:24:31.603449

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '094514885c4c'
down_revision = '1a6936ce2cb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_contractor', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('company_tax_number', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('company_tax_number')
        batch_op.drop_column('is_contractor')

    # ### end Alembic commands ###
