"""quote requests, machine catalog, quote settings

Revision ID: 1578ee9c2403
Revises: b6ae4e88bf57
Create Date: 2026-08-18 21:35:15.651206

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1578ee9c2403'
down_revision = 'b6ae4e88bf57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_machine_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ideal_for', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quote_machine_types', schema=None) as batch_op:
        batch_op.create_index('ix_quote_machine_types_active', ['active', 'sort_order'], unique=False)

    op.create_table('quote_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_template', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('serial', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.Column('contact_name', sa.String(length=256), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('tax_number', sa.String(length=32), nullable=False),
    sa.Column('address_zip', sa.String(length=16), nullable=False),
    sa.Column('address_city', sa.String(length=128), nullable=False),
    sa.Column('address_street', sa.String(length=256), nullable=False),
    sa.Column('address_number', sa.String(length=32), nullable=True),
    sa.Column('billing_zip', sa.String(length=16), nullable=True),
    sa.Column('billing_city', sa.String(length=128), nullable=True),
    sa.Column('billing_street', sa.String(length=256), nullable=True),
    sa.Column('billing_number', sa.String(length=32), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('machine_type_id', sa.Uuid(), nullable=True),
    sa.Column('machine_type_name', sa.String(length=256), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('price_per_portion', sa.Float(), nullable=True),
    sa.Column('min_portions', sa.Integer(), nullable=True),
    sa.Column('below_min_price', sa.Float(), nullable=True),
    sa.Column('rent_if_below_min', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('contract_text', sa.Text(), nullable=True),
    sa.Column('sign_token', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('signed_name', sa.String(length=256), nullable=True),
    sa.Column('signed_ip', sa.String(length=64), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('new','sent','signed','cancelled')", name='ck_quote_requests_status'),
    sa.ForeignKeyConstraint(['machine_type_id'], ['quote_machine_types.id'], name='fk_quotes_mtype', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name='fk_quotes_partner', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial', name='uq_quote_requests_serial')
    )
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.create_index('ix_quote_requests_status', ['status', 'created_at'], unique=False)
        batch_op.create_index('uq_quote_requests_sign_token', ['sign_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.drop_index('uq_quote_requests_sign_token')
        batch_op.drop_index('ix_quote_requests_status')

    op.drop_table('quote_requests')
    op.drop_table('quote_settings')
    with op.batch_alter_table('quote_machine_types', schema=None) as batch_op:
        batch_op.drop_index('ix_quote_machine_types_active')

    op.drop_table('quote_machine_types')
    # ### end Alembic commands ###
