"""baseline

Revision ID: 1761410c3a1e
Revises: 
Create Date: 2026-08-11 21:38:02.399294

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1761410c3a1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_provider', sa.String(length=16), nullable=False),
    sa.Column('anthropic_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('anthropic_model', sa.String(length=64), nullable=False),
    sa.Column('gemini_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('gemini_model', sa.String(length=64), nullable=False),
    sa.Column('assign_prompt', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("active_provider IN ('none','anthropic','gemini')", name='ck_ai_provider'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)

    op.create_table('billingo_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('pc_api_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('pc_block_id', sa.Integer(), nullable=True),
    sa.Column('pc_test_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('password_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('machine_label', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_by_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_entries', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_machine', ['machine_label'], unique=False)

    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_enabled', sa.Boolean(), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('send_hour', sa.Integer(), nullable=False),
    sa.Column('weekly_backup', sa.Boolean(), nullable=False),
    sa.Column('auto_receipt', sa.Boolean(), nullable=False),
    sa.Column('last_daily_sent', sa.String(length=10), nullable=True),
    sa.Column('last_backup_sent', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_code', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('invoicing_company', sa.String(length=8), nullable=True),
    sa.Column('partner_type', sa.String(length=16), nullable=False),
    sa.Column('tax_number', sa.String(length=32), nullable=True),
    sa.Column('eu_tax_number', sa.String(length=32), nullable=True),
    sa.Column('reg_number', sa.String(length=64), nullable=True),
    sa.Column('contact_name', sa.String(length=256), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('billing_address', sa.String(length=512), nullable=True),
    sa.Column('address_zip', sa.String(length=16), nullable=True),
    sa.Column('address_city', sa.String(length=128), nullable=True),
    sa.Column('address_street', sa.String(length=256), nullable=True),
    sa.Column('address_number', sa.String(length=32), nullable=True),
    sa.Column('billing_zip', sa.String(length=16), nullable=True),
    sa.Column('billing_city', sa.String(length=128), nullable=True),
    sa.Column('billing_street', sa.String(length=256), nullable=True),
    sa.Column('billing_number', sa.String(length=32), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('portal_token', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index('ix_partners_name', ['name'], unique=False)

    op.create_table('permission_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('grams_per_portion', sa.Integer(), nullable=False),
    sa.Column('price_per_portion', sa.Float(), nullable=False),
    sa.Column('vat_percent', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_name', ['name'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_skills_name')
    )
    op.create_table('support_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base', sa.Text(), nullable=True),
    sa.Column('auto_kb', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin','manager','uzletkoto','szervizes','employee')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('worksheet_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('company_address', sa.String(length=512), nullable=True),
    sa.Column('footer_text', sa.String(length=512), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('logo_data', sa.LargeBinary(), nullable=True),
    sa.Column('logo_mime', sa.String(length=32), nullable=True),
    sa.Column('show_materials', sa.Boolean(), nullable=False),
    sa.Column('show_hours', sa.Boolean(), nullable=False),
    sa.Column('show_client_signature', sa.Boolean(), nullable=False),
    sa.Column('show_comments', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('article_number', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('location_type', sa.String(length=64), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('norm', sa.Float(), nullable=True),
    sa.Column('tangible', sa.Boolean(), nullable=False),
    sa.Column('customer_owned', sa.Boolean(), nullable=False),
    sa.Column('contract_min_portions', sa.Integer(), nullable=True),
    sa.Column('contract_below_min_price', sa.Float(), nullable=True),
    sa.Column('rent_fee', sa.Float(), nullable=True),
    sa.Column('qr_token', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('in_stock','deployed','maintenance','retired')", name='ck_assets_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', name='uq_assets_barcode')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_partner', ['partner_id'], unique=False)
        batch_op.create_index('ix_assets_status', ['status'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employee_code', sa.String(length=6), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('birth_name', sa.String(length=256), nullable=True),
    sa.Column('mother_name', sa.String(length=256), nullable=True),
    sa.Column('birth_place', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('citizenship', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('residence_address', sa.String(length=512), nullable=True),
    sa.Column('tax_id_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('tax_id_masked', sa.String(length=16), nullable=True),
    sa.Column('taj_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('taj_masked', sa.String(length=16), nullable=True),
    sa.Column('bank_account_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('bank_account_masked', sa.String(length=16), nullable=True),
    sa.Column('wage_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=128), nullable=True),
    sa.Column('feor_code', sa.String(length=8), nullable=True),
    sa.Column('employment_type', sa.String(length=16), nullable=False),
    sa.Column('contract_type', sa.String(length=16), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('wage_type', sa.String(length=16), nullable=False),
    sa.Column('annual_leave_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("contract_type IN ('indefinite','fixed_term')", name='ck_employees_contract'),
    sa.CheckConstraint("employment_type IN ('full_time','part_time')", name='ck_employees_emp_type'),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_employees_status'),
    sa.CheckConstraint("wage_type IN ('monthly','hourly')", name='ck_employees_wage_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_employees_user')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('uq_employees_code', ['employee_code'], unique=True)

    op.create_table('partner_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('price_per_portion', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'product_id', name='uq_partner_price')
    )
    with op.batch_alter_table('partner_prices', schema=None) as batch_op:
        batch_op.create_index('ix_partner_prices_partner', ['partner_id'], unique=False)

    op.create_table('partner_stock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'product_id', name='uq_partner_stock')
    )
    with op.batch_alter_table('partner_stock', schema=None) as batch_op:
        batch_op.create_index('ix_partner_stock_partner', ['partner_id'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('settled_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('settled_by_name', sa.String(length=256), nullable=False),
    sa.Column('invoicing_company', sa.String(length=8), nullable=True),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('total_net', sa.Float(), nullable=False),
    sa.Column('total_gross', sa.Float(), nullable=False),
    sa.Column('invoiced', sa.Boolean(), nullable=False),
    sa.Column('billingo_document_id', sa.String(length=64), nullable=True),
    sa.Column('billingo_status', sa.String(length=16), nullable=True),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('partner_signature', sa.Text(), nullable=True),
    sa.Column('receipt_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash','card','transfer')", name='ck_settlement_payment'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index('ix_settlements_partner', ['partner_id', 'created_at'], unique=False)
        batch_op.create_index('ix_settlements_user', ['settled_by_user_id', 'created_at'], unique=False)

    op.create_table('asset_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.create_index('ix_asset_movements_asset', ['asset_id', 'created_at'], unique=False)

    op.create_table('asset_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_photos', schema=None) as batch_op:
        batch_op.create_index('ix_asset_photos_asset', ['asset_id'], unique=False)

    op.create_table('employee_skills',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'skill_id')
    )
    op.create_table('product_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_no', sa.String(length=16), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('partner_label', sa.String(length=256), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=256), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open','done','cancelled')", name='ck_order_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_status', ['status', 'created_at'], unique=False)

    op.create_table('service_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_no', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('asset_label', sa.String(length=256), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('partner_label', sa.String(length=256), nullable=True),
    sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=256), nullable=True),
    sa.Column('counter_at_service', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('parts', sa.JSON(), nullable=True),
    sa.Column('labor_fee', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('repair','maintenance')", name='ck_service_kind'),
    sa.CheckConstraint("priority IN ('low','normal','high')", name='ck_service_priority'),
    sa.CheckConstraint("status IN ('open','in_progress','done','cancelled')", name='ck_service_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.create_index('ix_service_asset', ['asset_id'], unique=False)
        batch_op.create_index('ix_service_status', ['status', 'created_at'], unique=False)

    op.create_table('settlement_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('settlement_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('previous_qty', sa.Float(), nullable=False),
    sa.Column('physical_qty', sa.Float(), nullable=False),
    sa.Column('consumed_qty', sa.Float(), nullable=False),
    sa.Column('portions', sa.Float(), nullable=False),
    sa.Column('price_per_portion', sa.Float(), nullable=False),
    sa.Column('vat_percent', sa.Integer(), nullable=False),
    sa.Column('amount_net', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_lines', schema=None) as batch_op:
        batch_op.create_index('ix_settlement_lines_settlement', ['settlement_id'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('role_label', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft','published')", name='ck_shifts_status'),
    sa.CheckConstraint('break_minutes >= 0', name='ck_shifts_break'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index('ix_shifts_date', ['work_date'], unique=False)
        batch_op.create_index('ix_shifts_employee_date', ['employee_id', 'work_date'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('quantity_delta', sa.Float(), nullable=False),
    sa.Column('settlement_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movements_partner', ['partner_id', 'created_at'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('required_skill_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open','done','needs_more_work')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_due', ['due_date'], unique=False)
        batch_op.create_index('ix_tasks_employee_due', ['employee_id', 'due_date'], unique=False)

    op.create_table('time_off_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected','cancelled')", name='ck_timeoff_status'),
    sa.CheckConstraint("type IN ('annual','sick','unpaid','other')", name='ck_timeoff_type'),
    sa.CheckConstraint('end_date >= start_date', name='ck_timeoff_range'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.create_index('ix_timeoff_employee', ['employee_id', 'start_date'], unique=False)

    op.create_table('task_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index('ix_task_comments_task', ['task_id', 'created_at'], unique=False)

    op.create_table('ticket_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_attachments_ticket', ['ticket_id'], unique=False)

    op.create_table('time_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('self','manual')", name='ck_timeentry_source'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index('ix_timeentry_employee', ['employee_id', 'clock_in'], unique=False)

    op.create_table('worksheets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('serial', sa.String(length=20), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=False),
    sa.Column('materials', sa.JSON(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=True),
    sa.Column('client_name', sa.String(length=256), nullable=True),
    sa.Column('client_location', sa.String(length=512), nullable=True),
    sa.Column('employee_signature', sa.Text(), nullable=True),
    sa.Column('client_signature', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial', name='uq_worksheets_serial'),
    sa.UniqueConstraint('task_id', name='uq_worksheets_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worksheets')
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_timeentry_employee')

    op.drop_table('time_entries')
    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_attachments_ticket')

    op.drop_table('ticket_attachments')
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_task_comments_task')

    op.drop_table('task_comments')
    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_timeoff_employee')

    op.drop_table('time_off_requests')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_employee_due')
        batch_op.drop_index('ix_tasks_due')

    op.drop_table('tasks')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_partner')

    op.drop_table('stock_movements')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index('ix_shifts_employee_date')
        batch_op.drop_index('ix_shifts_date')

    op.drop_table('shifts')
    with op.batch_alter_table('settlement_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_settlement_lines_settlement')

    op.drop_table('settlement_lines')
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_service_status')
        batch_op.drop_index('ix_service_asset')

    op.drop_table('service_tickets')
    with op.batch_alter_table('product_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status')

    op.drop_table('product_orders')
    op.drop_table('employee_skills')
    with op.batch_alter_table('asset_photos', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_photos_asset')

    op.drop_table('asset_photos')
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_movements_asset')

    op.drop_table('asset_movements')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index('ix_settlements_user')
        batch_op.drop_index('ix_settlements_partner')

    op.drop_table('settlements')
    with op.batch_alter_table('partner_stock', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_stock_partner')

    op.drop_table('partner_stock')
    with op.batch_alter_table('partner_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_prices_partner')

    op.drop_table('partner_prices')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('uq_employees_code')

    op.drop_table('employees')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_status')
        batch_op.drop_index('ix_assets_partner')

    op.drop_table('assets')
    op.drop_table('worksheet_settings')
    op.drop_table('users')
    op.drop_table('support_settings')
    op.drop_table('skills')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_name')

    op.drop_table('products')
    op.drop_table('permission_settings')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index('ix_partners_name')

    op.drop_table('partners')
    op.drop_table('notification_settings')
    with op.batch_alter_table('knowledge_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_machine')

    op.drop_table('knowledge_entries')
    op.drop_table('email_settings')
    op.drop_table('billingo_settings')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_created')

    op.drop_table('audit_events')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
