"""employee availability

Revision ID: 1a6936ce2cb4
Revises: 23d0e510baf6
Create Date: 2026-08-20 21:45:42.965424

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1a6936ce2cb4'
down_revision = '23d0e510baf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('availability')

    # ### end Alembic commands ###
