"""asset per-counter norms

Revision ID: 1bb6b282a309
Revises: 9860f83585e9
Create Date: 2026-08-20 19:04:45.102109

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1bb6b282a309'
down_revision = '9860f83585e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('norms', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('norms')

    # ### end Alembic commands ###
