"""worksheet external service flag

Revision ID: 23d0e510baf6
Revises: 1bb6b282a309
Create Date: 2026-08-20 21:23:27.445466

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '23d0e510baf6'
down_revision = '1bb6b282a309'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_service', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheets', schema=None) as batch_op:
        batch_op.drop_column('external_service')

    # ### end Alembic commands ###
