"""multi-counter machines

Revision ID: 458650400d1f
Revises: 424f8fa8f10b
Create Date: 2026-08-12 20:58:08.325152

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '458650400d1f'
down_revision = '424f8fa8f10b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        # server_default kell: a meglévő (nem üres) assets táblán a NOT NULL
        # oszlop csak kitöltött alapértékkel adható hozzá.
        batch_op.add_column(sa.Column(
            'counter_count', sa.Integer(), nullable=False, server_default='1',
        ))
        batch_op.add_column(sa.Column('counters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('counters')
        batch_op.drop_column('counter_count')

    # ### end Alembic commands ###
