"""machine type image

Revision ID: 6c5dbb03d795
Revises: 1578ee9c2403
Create Date: 2026-08-18 22:11:46.961205

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6c5dbb03d795'
down_revision = '1578ee9c2403'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_machine_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mime', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_machine_types', schema=None) as batch_op:
        batch_op.drop_column('image_mime')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
