"""product category

Revision ID: 77a8cc6054b6
Revises: dd69e9bad25f
Create Date: 2026-08-16 21:13:23.957361

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '77a8cc6054b6'
down_revision = 'dd69e9bad25f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
