"""employee payroll source

Revision ID: 791a5e1fe049
Revises: 094514885c4c
Create Date: 2026-08-22 23:41:47.628126

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '791a5e1fe049'
down_revision = '094514885c4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_source', sa.String(length=16), nullable=False, server_default='attendance'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('payroll_source')

    # ### end Alembic commands ###
