"""contract schedule payment and product consignment flag

Revision ID: 83cb8b113530
Revises: 791a5e1fe049
Create Date: 2026-08-23 13:18:06.951113

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '83cb8b113530'
down_revision = '791a5e1fe049'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_weeks', sa.Integer(), server_default='4', nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('payment_terms_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_settlement_weeks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_payment_method', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('contract_payment_terms_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_consignment', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Visszatöltés: a kg-ban kezelt (kávé-jellegű) termékek bizományosak —
    # minden más eladás (átadáskor azonnal fizetendő).
    op.execute("UPDATE products SET is_consignment = true WHERE unit = 'kg'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_consignment')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('contract_payment_terms_days')
        batch_op.drop_column('contract_payment_method')
        batch_op.drop_column('contract_settlement_weeks')

    with op.batch_alter_table('partner_contracts', schema=None) as batch_op:
        batch_op.drop_column('payment_terms_days')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('settlement_weeks')

    # ### end Alembic commands ###
