"""machine settlement + debt tracking

Revision ID: 8ac1b1644854
Revises: 458650400d1f
Create Date: 2026-08-12 22:14:30.277482

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8ac1b1644854'
down_revision = '458650400d1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_machines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('settlement_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('asset_name', sa.String(length=256), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=True),
    sa.Column('prev_counter', sa.Integer(), nullable=False),
    sa.Column('new_counter', sa.Integer(), nullable=False),
    sa.Column('service_portions', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('portions_billed', sa.Float(), nullable=False),
    sa.Column('price_per_portion', sa.Float(), nullable=False),
    sa.Column('amount_net', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_machines', schema=None) as batch_op:
        batch_op.create_index('ix_settlement_machines_asset', ['asset_id', 'created_at'], unique=False)
        batch_op.create_index('ix_settlement_machines_settlement', ['settlement_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_product_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'fk_assets_default_product', 'products',
            ['default_product_id'], ['id'], ondelete='SET NULL',
        )

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debt_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paid_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('debt_before')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_default_product', type_='foreignkey')
        batch_op.drop_column('default_product_id')

    with op.batch_alter_table('settlement_machines', schema=None) as batch_op:
        batch_op.drop_index('ix_settlement_machines_settlement')
        batch_op.drop_index('ix_settlement_machines_asset')

    op.drop_table('settlement_machines')
    # ### end Alembic commands ###
