"""telegram event selection

Revision ID: 9250fdc017bf
Revises: b3294bc83e98
Create Date: 2026-08-23 14:55:18.273141

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9250fdc017bf'
down_revision = 'b3294bc83e98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tg_events', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_column('tg_events')

    # ### end Alembic commands ###
