"""quote agent user

Revision ID: 9860f83585e9
Revises: 6c5dbb03d795
Create Date: 2026-08-20 18:59:50.171913

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9860f83585e9'
down_revision = '6c5dbb03d795'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_user_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_quotes_agent', 'users', ['agent_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quotes_agent', type_='foreignkey')
        batch_op.drop_column('agent_user_id')

    # ### end Alembic commands ###
