"""partner latlng for routing

Revision ID: a56e2374df03
Revises: a3f2c9d81b47
Create Date: 2026-08-14 20:55:49.742327

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a56e2374df03'
down_revision = 'a3f2c9d81b47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
