"""agents expenses no minimum whatsapp telegram

Revision ID: b3294bc83e98
Revises: 83cb8b113530
Create Date: 2026-08-23 13:47:00.076591

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b3294bc83e98'
down_revision = '83cb8b113530'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount_gross', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_agent_expenses_creator', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_agent_expenses_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_expenses', schema=None) as batch_op:
        batch_op.create_index('ix_agent_expenses_user', ['user_id', 'expense_date'], unique=False)

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('wa_token_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('wa_phone_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('wa_recipients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tg_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('tg_token_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('tg_chat_ids', sa.Text(), nullable=True))

    with op.batch_alter_table('partner_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_minimum', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_no_minimum', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('agent_user_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_partners_agent', 'users', ['agent_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substitute_user_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_users_substitute', 'users', ['substitute_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_substitute', type_='foreignkey')
        batch_op.drop_column('substitute_user_id')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_constraint('fk_partners_agent', type_='foreignkey')
        batch_op.drop_column('agent_user_id')
        batch_op.drop_column('contract_no_minimum')

    with op.batch_alter_table('partner_contracts', schema=None) as batch_op:
        batch_op.drop_column('no_minimum')

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_column('tg_chat_ids')
        batch_op.drop_column('tg_token_encrypted')
        batch_op.drop_column('tg_enabled')
        batch_op.drop_column('wa_recipients')
        batch_op.drop_column('wa_phone_id')
        batch_op.drop_column('wa_token_encrypted')
        batch_op.drop_column('wa_enabled')

    with op.batch_alter_table('agent_expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_expenses_user')

    op.drop_table('agent_expenses')
    # ### end Alembic commands ###
