"""delivery notes

Revision ID: b6ae4e88bf57
Revises: f4d4aee35973
Create Date: 2026-08-16 22:08:26.814809

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b6ae4e88bf57'
down_revision = 'f4d4aee35973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('serial', sa.String(length=20), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('settlement_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_by_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open','settled','cancelled')", name='ck_delivery_notes_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_delivery_notes_user', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name='fk_delivery_notes_partner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name='fk_delivery_notes_settlement', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], name='fk_delivery_notes_wh', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial', name='uq_delivery_notes_serial')
    )
    with op.batch_alter_table('delivery_notes', schema=None) as batch_op:
        batch_op.create_index('ix_delivery_notes_partner', ['partner_id', 'status'], unique=False)

    op.create_table('delivery_note_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_note_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('vat_percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], name='fk_dn_lines_note', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_dn_lines_product', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_note_lines', schema=None) as batch_op:
        batch_op.create_index('ix_delivery_note_lines_note', ['delivery_note_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_note_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_note_lines_note')

    op.drop_table('delivery_note_lines')
    with op.batch_alter_table('delivery_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_notes_partner')

    op.drop_table('delivery_notes')
    # ### end Alembic commands ###
