"""employee telegram link

Revision ID: b7695b1363ed
Revises: 9250fdc017bf
Create Date: 2026-08-23 17:14:45.938547

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b7695b1363ed'
down_revision = '9250fdc017bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=32), nullable=True))

    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tg_update_offset', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.drop_column('tg_update_offset')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
