"""maintenance fee and worksheet asset link

Revision ID: bc2c06015352
Revises: b7695b1363ed
Create Date: 2026-08-23 19:22:22.173494

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'bc2c06015352'
down_revision = 'b7695b1363ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_fee', sa.Float(), nullable=True))

    with op.batch_alter_table('worksheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fee_discount', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('billingo_document_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('invoice_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_worksheets_asset', 'assets', ['asset_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worksheets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_worksheets_asset', type_='foreignkey')
        batch_op.drop_column('invoice_sent_at')
        batch_op.drop_column('billingo_document_id')
        batch_op.drop_column('fee_discount')
        batch_op.drop_column('maintenance_fee')
        batch_op.drop_column('asset_id')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('maintenance_fee')

    # ### end Alembic commands ###
