"""no-vat settlements, counter cross-check, per-partner stock minimum

Revision ID: c911f13f2a6c
Revises: cdeb6b54016f
Create Date: 2026-08-12 17:21:24.529550

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c911f13f2a6c'
down_revision = 'cdeb6b54016f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_quantity', sa.Float(), nullable=True))

    with op.batch_alter_table('settlement_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter_portions', sa.Float(), nullable=True))

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        # server_default kell: a meglévő (nem üres) settlements táblán a
        # NOT NULL oszlop csak kitöltött alapértékkel adható hozzá.
        batch_op.add_column(sa.Column(
            'no_vat', sa.Boolean(), nullable=False, server_default=sa.false(),
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_column('no_vat')

    with op.batch_alter_table('settlement_lines', schema=None) as batch_op:
        batch_op.drop_column('counter_portions')

    with op.batch_alter_table('partner_stock', schema=None) as batch_op:
        batch_op.drop_column('min_quantity')

    # ### end Alembic commands ###
