"""purchase price + partner contract terms

Revision ID: cdeb6b54016f
Revises: 1761410c3a1e
Create Date: 2026-08-12 16:55:03.202874

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'cdeb6b54016f'
down_revision = '1761410c3a1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_min_portions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contract_below_min_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contract_min_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contract_below_min_price_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contract_no_min_until', sa.Date(), nullable=True))
        # server_default kell: a meglévő (nem üres) partners táblán a NOT NULL
        # oszlop csak kitöltött alapértékkel adható hozzá.
        batch_op.add_column(sa.Column(
            'contract_rent_if_below_min', sa.Boolean(),
            nullable=False, server_default=sa.false(),
        ))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_column('unit_cost')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('purchase_price')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('contract_rent_if_below_min')
        batch_op.drop_column('contract_no_min_until')
        batch_op.drop_column('contract_below_min_price_kg')
        batch_op.drop_column('contract_min_kg')
        batch_op.drop_column('contract_below_min_price')
        batch_op.drop_column('contract_min_portions')

    # ### end Alembic commands ###
