"""partner contracts entity

Revision ID: f4d4aee35973
Revises: e4b1a7c25f90
Create Date: 2026-08-16 21:53:08.441890

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f4d4aee35973'
down_revision = 'e4b1a7c25f90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('min_portions', sa.Integer(), nullable=True),
    sa.Column('below_min_price', sa.Float(), nullable=True),
    sa.Column('min_kg', sa.Float(), nullable=True),
    sa.Column('below_min_price_kg', sa.Float(), nullable=True),
    sa.Column('rent_if_below_min', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_partner_contracts_user', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name='fk_partner_contracts_partner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_contracts', schema=None) as batch_op:
        batch_op.create_index('ix_partner_contracts_partner', ['partner_id', 'valid_from'], unique=False)

    # ### end Alembic commands ###

    # Adat-átvezetés: a partnereken lévő szerződés-mezőkből egy-egy szerződés-
    # sor. Türelmi időszaknál (contract_no_min_until a jövőben) a szerződés a
    # türelmi idő lejárta UTÁN lép érvénybe — addig nincs aktív szerződés, ami
    # a korábbi viselkedéssel azonos (minimum szünetel).
    import uuid as uuid_mod
    from datetime import date, timedelta

    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "SELECT id, contract_min_portions, contract_below_min_price, "
        "contract_min_kg, contract_below_min_price_kg, contract_no_min_until, "
        "contract_rent_if_below_min FROM partners "
        "WHERE contract_min_portions IS NOT NULL OR contract_min_kg IS NOT NULL "
        "OR contract_rent_if_below_min = :t OR contract_below_min_price IS NOT NULL"
    ), {"t": True}).fetchall()
    contracts_table = sa.table(
        "partner_contracts",
        sa.column("id", sa.Uuid()),
        sa.column("partner_id", sa.Uuid()),
        sa.column("valid_from", sa.Date()),
        sa.column("valid_to", sa.Date()),
        sa.column("min_portions", sa.Integer()),
        sa.column("below_min_price", sa.Float()),
        sa.column("min_kg", sa.Float()),
        sa.column("below_min_price_kg", sa.Float()),
        sa.column("rent_if_below_min", sa.Boolean()),
        sa.column("note", sa.Text()),
    )
    payload = []
    for r in rows:
        no_min_until = r[5]
        if isinstance(no_min_until, str):
            no_min_until = date.fromisoformat(no_min_until)
        start = (
            no_min_until + timedelta(days=1)
            if no_min_until and no_min_until >= date.today()
            else date(2020, 1, 1)
        )
        payload.append({
            "id": uuid_mod.uuid4(),
            "partner_id": r[0],
            "valid_from": start,
            "valid_to": None,
            "min_portions": r[1],
            "below_min_price": r[2],
            "min_kg": r[3],
            "below_min_price_kg": r[4],
            "rent_if_below_min": bool(r[6]),
            "note": "Átvezetve a partner-adatlapról",
        })
    if payload:
        op.bulk_insert(contracts_table, payload)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner_contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_partner_contracts_partner')

    op.drop_table('partner_contracts')
    # ### end Alembic commands ###
